In [1]:
import pandas as pd
import numpy  as np
import matplotlib.pyplot as plt
import seaborn as sns
from persiantools.jdatetime import JalaliDate
import jalali_pandas
import pandas_ta  as ta

In [2]:
df = pd.read_csv(r'../data/IRMCI.csv', encoding='utf-8')
df.head()

,ticker,miladi,open,high,low,close,volume,value,transaction_count,lastday_price,shamsi,last_price
0,همراه,20130820,42000.0,1000.0,42000.0,42001.0,546520,2.295462e+10,69,1000.0,13920529,42200.0
1,همراه,20130821,42009.0,42001.0,42005.0,42142.0,161499,6.929039e+09,214,42001.0,13920530,43400.0
2,همراه,20130824,43300.0,42142.0,42222.0,42191.0,110913,4.724576e+09,168,42142.0,13920602,42222.0
3,همراه,20130825,42860.0,42191.0,42453.0,42213.0,67490,2.869908e+09,94,42191.0,13920603,42550.0
4,همراه,20130826,42401.0,42213.0,42036.0,42214.0,160307,6.768045e+09,121,42213.0,13920604,42050.0

In [3]:
df['Gregorian_Date'] = pd.to_datetime(df['miladi'], format='%Y%m%d')
df["Jalali_Date"] = df["Gregorian_Date"].jalali.to_jalali()
df['year'] = df["Jalali_Date"].jalali.year
df['month'] = df["Jalali_Date"].jalali.month
df['day'] = df["Jalali_Date"].jalali.day
df['weekday'] = df["Jalali_Date"].jalali.weekday
df.drop(['ticker','shamsi','miladi'],axis=1,inplace=True)

In [4]:
df

,open,high,low,close,volume,value,transaction_count,lastday_price,last_price,Gregorian_Date,Jalali_Date,year,month,day,weekday
0,42000.0,1000.0,42000.0,42001.0,546520,2.295462e+10,69,1000.0,42200.0,2013-08-20,1392-05-29 00:00:00,1392,5,29,3
1,42009.0,42001.0,42005.0,42142.0,161499,6.929039e+09,214,42001.0,43400.0,2013-08-21,1392-05-30 00:00:00,1392,5,30,4
2,43300.0,42142.0,42222.0,42191.0,110913,4.724576e+09,168,42142.0,42222.0,2013-08-24,1392-06-02 00:00:00,1392,6,2,0
3,42860.0,42191.0,42453.0,42213.0,67490,2.869908e+09,94,42191.0,42550.0,2013-08-25,1392-06-03 00:00:00,1392,6,3,1
4,42401.0,42213.0,42036.0,42214.0,160307,6.768045e+09,121,42213.0,42050.0,2013-08-26,1392-06-04 00:00:00,1392,6,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2725,4433.0,4304.0,4323.0,4373.0,21880282,9.612792e+10,602,4304.0,4350.0,2024-12-03,1403-09-13 00:00:00,1403,9,13,3
2726,4400.0,4373.0,4330.0,4368.0,13576844,5.922970e+10,626,4373.0,4366.0,2024-12-04,1403-09-14 00:00:00,1403,9,14,4
2727,4331.0,4368.0,4260.0,4350.0,13113559,5.679588e+10,847,4368.0,4355.0,2024-12-07,1403-09-17 00:00:00,1403,9,17,0
2728,4267.0,4350.0,4240.0,4407.0,45694622,2.013663e+11,1124,4350.0,4410.0,2024-12-08,1403-09-18 00:00:00,1403,9,18,1
2729,4479.0,4407.0,4460.0,4536.0,58729010,2.663827e+11,926,4407.0,4539.0,2024-12-09,1403-09-19 00:00:00,1403,9,19,2

In [5]:
df.ta.ema(df['close'], length=5, offset=None, append=True)
df.ta.ema(df['close'], length=10, offset=None, append=True)
df.ta.ema(df['close'], length=30, offset=None, append=True)

TypeError: AnalysisIndicators.ema() got multiple values for argument 'length'

In [22]:
df['ema_5'] = df.ta.ema(5)
df['ema_10'] = df.ta.ema(10)
df['ema_20'] = df.ta.ema(20)
df['ema_40'] = df.ta.ema(40)
df['ema_60'] = df.ta.ema(60)

df['sma_5'] = df.ta.sma(5)
df['sma_10'] = df.ta.sma(10)
df['sma_20'] = df.ta.sma(20)
df['sma_40'] = df.ta.sma(40)
df['sma_60'] = df.ta.sma(60)

df['trima_5'] = df.ta.trima(5)
df['trima_10'] = df.ta.trima(10)
df['trima_20'] = df.ta.trima(20)
df['trima_40'] = df.ta.trima(40)
df['trima_60'] = df.ta.trima(60)

df['rsi_5'] = df.ta.rsi(5)
df['rsi_10'] = df.ta.rsi(10)
df['rsi_20'] = df.ta.rsi(20)
df['rsi_40'] = df.ta.rsi(40)
df['rsi_60'] = df.ta.rsi(60)

# df['macd'] = df.ta.macd()
# df['stoch'] = df.ta.stoch()

In [18]:
df.columns

Index(['open', 'high', 'low', 'close', 'volume', 'value', 'transaction_count',
       'lastday_price', 'last_price', 'Gregorian_Date', 'Jalali_Date', 'year',
       'month', 'day', 'weekday', 'ema_5', 'ema_10', 'ema_20', 'sma_5',
       'sma_10', 'sma_20', 'trima_5', 'trima_10', 'trima_20', 'ema_40',
       'ema_60', 'sma_40', 'sma_60', 'trima_40', 'trima_60'],
      dtype='object')

In [10]:
df.ta.indicators()

Pandas TA - Technical Analysis Indicators - v0.3.14b0
Total Indicators & Utilities: 205
Abbreviations:
    aberration, above, above_value, accbands, ad, adosc, adx, alma, amat, ao, aobv, apo, aroon, atr, bbands, below, below_value, bias, bop, brar, cci, cdl_pattern, cdl_z, cfo, cg, chop, cksp, cmf, cmo, coppock, cross, cross_value, cti, decay, decreasing, dema, dm, donchian, dpo, ebsw, efi, ema, entropy, eom, er, eri, fisher, fwma, ha, hilo, hl2, hlc3, hma, hwc, hwma, ichimoku, increasing, inertia, jma, kama, kc, kdj, kst, kurtosis, kvo, linreg, log_return, long_run, macd, mad, massi, mcgd, median, mfi, midpoint, midprice, mom, natr, nvi, obv, ohlc4, pdist, percent_return, pgo, ppo, psar, psl, pvi, pvo, pvol, pvr, pvt, pwma, qqe, qstick, quantile, rma, roc, rsi, rsx, rvgi, rvi, short_run, sinwma, skew, slope, sma, smi, squeeze, squeeze_pro, ssf, stc, stdev, stoch, stochrsi, supertrend, swma, t3, td_seq, tema, thermo, tos_stdevall, trima, trix, true_range, tsi, tsignals, ttm_trend, ui, uo, variance, vhf, vidya, vortex, vp, vwap, vwma, wcp, willr, wma, xsignals, zlma, zscore

Candle Patterns:
    2crows, 3blackcrows, 3inside, 3linestrike, 3outside, 3starsinsouth, 3whitesoldiers, abandonedbaby, advanceblock, belthold, breakaway, closingmarubozu, concealbabyswall, counterattack, darkcloudcover, doji, dojistar, dragonflydoji, engulfing, eveningdojistar, eveningstar, gapsidesidewhite, gravestonedoji, hammer, hangingman, harami, haramicross, highwave, hikkake, hikkakemod, homingpigeon, identical3crows, inneck, inside, invertedhammer, kicking, kickingbylength, ladderbottom, longleggeddoji, longline, marubozu, matchinglow, mathold, morningdojistar, morningstar, onneck, piercing, rickshawman, risefall3methods, separatinglines, shootingstar, shortline, spinningtop, stalledpattern, sticksandwich, takuri, tasukigap, thrusting, tristar, unique3river, upsidegap2crows, xsidegap3methods

In [20]:
df.ta.rsi(10)

0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
          ...
2725    94.406851
2726    92.981053
2727    87.683993
2728    89.740485
2729    92.774400
Name: RSI_10, Length: 2730, dtype: float64